"""empty message

Revision ID: 21375e79362d
Revises: 
Create Date: 2020-07-24 21:45:14.589226

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21375e79362d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ambulancias',
    sa.Column('id_ambulancia', sa.Integer(), nullable=False),
    sa.Column('num_unidad', sa.String(length=10), nullable=True),
    sa.Column('id_servicio', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_ambulancia')
    )
    op.create_table('bitacora',
    sa.Column('id_bitacora', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('id_movimiento', sa.Integer(), nullable=True),
    sa.Column('tipo_movimiento', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_bitacora')
    )
    op.create_table('colonias',
    sa.Column('id_colonia', sa.Integer(), nullable=False),
    sa.Column('nombre_colonia', sa.String(length=70), nullable=True),
    sa.Column('id_municipio', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_colonia')
    )
    op.create_table('hospitales',
    sa.Column('id_hospital', sa.Integer(), nullable=False),
    sa.Column('id_municipio', sa.Integer(), nullable=True),
    sa.Column('nombre_hospital', sa.String(length=70), nullable=True),
    sa.Column('direccion', sa.String(length=70), nullable=True),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id_hospital')
    )
    op.create_table('movimientos',
    sa.Column('id_movimiento', sa.Integer(), nullable=False),
    sa.Column('id_paciente', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('id_hospital', sa.Integer(), nullable=True),
    sa.Column('id_ambulancia', sa.Integer(), nullable=True),
    sa.Column('id_colonia', sa.Integer(), nullable=True),
    sa.Column('id_urgencia', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_final', sa.DateTime(), nullable=True),
    sa.Column('presion_arterial', sa.String(length=10), nullable=True),
    sa.Column('frec_cardiaca', sa.String(length=10), nullable=True),
    sa.Column('frec_respiratoria', sa.String(length=10), nullable=True),
    sa.Column('temperatura', sa.String(length=2), nullable=True),
    sa.Column('escala_glassgow', sa.String(length=10), nullable=True),
    sa.Column('gravedad', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id_movimiento')
    )
    op.create_table('municipios',
    sa.Column('id_municipio', sa.Integer(), nullable=False),
    sa.Column('nombre_municipio', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id_municipio')
    )
    op.create_table('pacientes',
    sa.Column('id_paciente', sa.Integer(), nullable=False),
    sa.Column('servicio_medico', sa.String(length=70), nullable=True),
    sa.Column('nombre_paciente', sa.String(length=70), nullable=True),
    sa.Column('apellidos', sa.String(length=100), nullable=True),
    sa.Column('genero', sa.String(length=1), nullable=True),
    sa.Column('fecha_nac', sa.DateTime(), nullable=True),
    sa.Column('id_colonia', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_paciente')
    )
    op.create_table('servicios',
    sa.Column('id_servicio', sa.Integer(), nullable=False),
    sa.Column('servicio_nombre', sa.String(length=10), nullable=True),
    sa.Column('contacto', sa.String(length=70), nullable=True),
    sa.Column('telefono', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id_servicio')
    )
    op.create_table('tipo_movimiento',
    sa.Column('id_tipo_movimiento', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_movimiento')
    )
    op.create_table('tipo_usuario',
    sa.Column('id_tipo_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo_usuario', sa.String(length=70), nullable=True),
    sa.Column('registro', sa.Boolean(), nullable=True),
    sa.Column('medico_reg', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_usuario')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=70), nullable=True),
    sa.Column('id_tipo_usuario', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios')
    op.drop_table('tipo_usuario')
    op.drop_table('tipo_movimiento')
    op.drop_table('servicios')
    op.drop_table('pacientes')
    op.drop_table('municipios')
    op.drop_table('movimientos')
    op.drop_table('hospitales')
    op.drop_table('colonias')
    op.drop_table('bitacora')
    op.drop_table('ambulancias')
    # ### end Alembic commands ###
