"""empty message

Revision ID: 554bc67e7ec5
Revises: 21375e79362d
Create Date: 2020-08-03 14:00:03.086235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '554bc67e7ec5'
down_revision = '21375e79362d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('urgencia',
    sa.Column('id_urgencia', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id_urgencia'),
    schema='public'
    )
    op.drop_table('tipo_movimiento')
    op.alter_column('ambulancias', 'id_servicio',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'ambulancias', 'servicios', ['id_servicio'], ['id_servicio'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'bitacora', 'movimientos', ['id_movimiento'], ['id_movimiento'], source_schema='public', referent_schema='public')
    op.alter_column('colonias', 'id_municipio',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'colonias', 'municipios', ['id_municipio'], ['id_municipio'], source_schema='public', referent_schema='public')
    op.alter_column('hospitales', 'id_municipio',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'hospitales', 'municipios', ['id_municipio'], ['id_municipio'], source_schema='public', referent_schema='public')
    op.alter_column('movimientos', 'id_ambulancia',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movimientos', 'id_hospital',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movimientos', 'id_paciente',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('movimientos', 'id_usuario',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'movimientos', 'ambulancias', ['id_ambulancia'], ['id_ambulancia'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'movimientos', 'pacientes', ['id_paciente'], ['id_paciente'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'movimientos', 'hospitales', ['id_hospital'], ['id_hospital'], source_schema='public', referent_schema='public')
    op.create_foreign_key(None, 'movimientos', 'usuarios', ['id_usuario'], ['id_usuario'], source_schema='public', referent_schema='public')
    op.drop_column('movimientos', 'id_urgencia')
    op.alter_column('pacientes', 'id_colonia',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'pacientes', 'colonias', ['id_colonia'], ['id_colonia'], source_schema='public', referent_schema='public')
    op.alter_column('usuarios', 'id_tipo_usuario',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'usuarios', 'tipo_usuario', ['id_tipo_usuario'], ['id_tipo_usuario'], source_schema='public', referent_schema='public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', schema='public', type_='foreignkey')
    op.alter_column('usuarios', 'id_tipo_usuario',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'pacientes', schema='public', type_='foreignkey')
    op.alter_column('pacientes', 'id_colonia',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('movimientos', sa.Column('id_urgencia', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'movimientos', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'movimientos', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'movimientos', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'movimientos', schema='public', type_='foreignkey')
    op.alter_column('movimientos', 'id_usuario',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movimientos', 'id_paciente',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movimientos', 'id_hospital',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('movimientos', 'id_ambulancia',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'hospitales', schema='public', type_='foreignkey')
    op.alter_column('hospitales', 'id_municipio',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'colonias', schema='public', type_='foreignkey')
    op.alter_column('colonias', 'id_municipio',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'bitacora', schema='public', type_='foreignkey')
    op.drop_constraint(None, 'ambulancias', schema='public', type_='foreignkey')
    op.alter_column('ambulancias', 'id_servicio',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_table('tipo_movimiento',
    sa.Column('id_tipo_movimiento', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('descripcion', sa.VARCHAR(length=70), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_tipo_movimiento', name='tipo_movimiento_pkey')
    )
    op.drop_table('urgencia', schema='public')
    # ### end Alembic commands ###
